export interface Food {
  id: string
  name: string
  category: string
  calories: number // per 100g
  protein: number // per 100g
  carbs: number // per 100g
  fats: number // per 100g
  fiber: number // per 100g
  dietaryTags: string[] // vegan, vegetarian, keto, etc.
  allergens: string[]
  servingSize: number // in grams
  servingUnit: string
}

export const foodDatabase: Food[] = [
  // Proteins
  {
    id: "chicken-breast",
    name: "Chicken Breast",
    category: "protein",
    calories: 165,
    protein: 31,
    carbs: 0,
    fats: 3.6,
    fiber: 0,
    dietaryTags: [],
    allergens: [],
    servingSize: 100,
    servingUnit: "g",
  },
  {
    id: "salmon",
    name: "Salmon",
    category: "protein",
    calories: 208,
    protein: 25,
    carbs: 0,
    fats: 12,
    fiber: 0,
    dietaryTags: ["keto"],
    allergens: ["fish"],
    servingSize: 100,
    servingUnit: "g",
  },
  {
    id: "tofu",
    name: "Tofu",
    category: "protein",
    calories: 76,
    protein: 8,
    carbs: 1.9,
    fats: 4.8,
    fiber: 0.3,
    dietaryTags: ["vegan", "vegetarian"],
    allergens: ["soy"],
    servingSize: 100,
    servingUnit: "g",
  },
  {
    id: "greek-yogurt",
    name: "Greek Yogurt",
    category: "protein",
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fats: 0.4,
    fiber: 0,
    dietaryTags: ["vegetarian"],
    allergens: ["dairy"],
    servingSize: 100,
    servingUnit: "g",
  },
  {
    id: "eggs",
    name: "Eggs",
    category: "protein",
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fats: 11,
    fiber: 0,
    dietaryTags: ["vegetarian", "keto"],
    allergens: ["eggs"],
    servingSize: 100,
    servingUnit: "g",
  },
  {
    id: "lentils",
    name: "Lentils",
    category: "protein",
    calories: 116,
    protein: 9,
    carbs: 20,
    fats: 0.4,
    fiber: 8,
    dietaryTags: ["vegan", "vegetarian"],
    allergens: [],
    servingSize: 100,
    servingUnit: "g",
  },

  // Carbohydrates
  {
    id: "brown-rice",
    name: "Brown Rice",
    category: "carbs",
    calories: 111,
    protein: 2.6,
    carbs: 23,
    fats: 0.9,
    fiber: 1.8,
    dietaryTags: ["vegan", "vegetarian"],
    allergens: [],
    servingSize: 100,
    servingUnit: "g",
  },
  {
    id: "quinoa",
    name: "Quinoa",
    category: "carbs",
    calories: 120,
    protein: 4.4,
    carbs: 22,
    fats: 1.9,
    fiber: 2.8,
    dietaryTags: ["vegan", "vegetarian"],
    allergens: [],
    servingSize: 100,
    servingUnit: "g",
  },
  {
    id: "sweet-potato",
    name: "Sweet Potato",
    category: "carbs",
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fats: 0.1,
    fiber: 3,
    dietaryTags: ["vegan", "vegetarian"],
    allergens: [],
    servingSize: 100,
    servingUnit: "g",
  },
  {
    id: "oats",
    name: "Oats",
    category: "carbs",
    calories: 389,
    protein: 16.9,
    carbs: 66,
    fats: 6.9,
    fiber: 10.6,
    dietaryTags: ["vegan", "vegetarian"],
    allergens: ["gluten"],
    servingSize: 100,
    servingUnit: "g",
  },

  // Vegetables
  {
    id: "broccoli",
    name: "Broccoli",
    category: "vegetables",
    calories: 34,
    protein: 2.8,
    carbs: 7,
    fats: 0.4,
    fiber: 2.6,
    dietaryTags: ["vegan", "vegetarian", "keto"],
    allergens: [],
    servingSize: 100,
    servingUnit: "g",
  },
  {
    id: "spinach",
    name: "Spinach",
    category: "vegetables",
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fats: 0.4,
    fiber: 2.2,
    dietaryTags: ["vegan", "vegetarian", "keto"],
    allergens: [],
    servingSize: 100,
    servingUnit: "g",
  },
  {
    id: "avocado",
    name: "Avocado",
    category: "fats",
    calories: 160,
    protein: 2,
    carbs: 9,
    fats: 15,
    fiber: 7,
    dietaryTags: ["vegan", "vegetarian", "keto"],
    allergens: [],
    servingSize: 100,
    servingUnit: "g",
  },

  // Fats
  {
    id: "olive-oil",
    name: "Olive Oil",
    category: "fats",
    calories: 884,
    protein: 0,
    carbs: 0,
    fats: 100,
    fiber: 0,
    dietaryTags: ["vegan", "vegetarian", "keto"],
    allergens: [],
    servingSize: 15,
    servingUnit: "ml",
  },
  {
    id: "almonds",
    name: "Almonds",
    category: "fats",
    calories: 579,
    protein: 21,
    carbs: 22,
    fats: 50,
    fiber: 12,
    dietaryTags: ["vegan", "vegetarian", "keto"],
    allergens: ["nuts"],
    servingSize: 30,
    servingUnit: "g",
  },
  {
    id: "chia-seeds",
    name: "Chia Seeds",
    category: "fats",
    calories: 486,
    protein: 17,
    carbs: 42,
    fats: 31,
    fiber: 34,
    dietaryTags: ["vegan", "vegetarian"],
    allergens: [],
    servingSize: 15,
    servingUnit: "g",
  },

  // Fruits
  {
    id: "banana",
    name: "Banana",
    category: "fruits",
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fats: 0.3,
    fiber: 2.6,
    dietaryTags: ["vegan", "vegetarian"],
    allergens: [],
    servingSize: 100,
    servingUnit: "g",
  },
  {
    id: "berries",
    name: "Mixed Berries",
    category: "fruits",
    calories: 57,
    protein: 0.7,
    carbs: 14,
    fats: 0.3,
    fiber: 2.4,
    dietaryTags: ["vegan", "vegetarian", "keto"],
    allergens: [],
    servingSize: 100,
    servingUnit: "g",
  },
]

export function getFoodsByCategory(category: string): Food[] {
  return foodDatabase.filter((food) => food.category === category)
}

export function getFoodsByDietaryTags(tags: string[]): Food[] {
  return foodDatabase.filter((food) => tags.some((tag) => food.dietaryTags.includes(tag)))
}

export function getFoodsWithoutAllergens(allergens: string[]): Food[] {
  return foodDatabase.filter((food) => !food.allergens.some((allergen) => allergens.includes(allergen)))
}
